# You must run "make env" (at the root level) before these stages will run
stages:
{%- for res in results %}
  build-case-{{res}}:
    wdir: results
    cmd: 
      - omc {{res}}.mos
      - rm {{res}}_*.c {{res}}.c {{res}}.o {{res}}_*.h {{res}}_*.o {{res}}.libs {{res}}.log {{res}}.makefile {{res}}_prof*
    deps:
      - ../build-arch
      - {{res}}.mos
      - ../../ModelicaByExample
    outs:
      - {{res}}_info.json
      - {{res}}_init.xml
      - {{res}}_res.mat
      - {{res}}
{%- endfor %}
  build-exes:
    wdir: results
    cmd:
      - tar cf exes.tar.gz {% for res in results %} {{ res }} {% endfor %}
    deps:
{%- for res in results %}
      - {{res}}
{%- endfor %}
    outs:
      - exes.tar.gz