stages:
  build-specs:
    wdir: text
    cmd:
      - mkdir -p results/json
      - mkdir -p plots
      - python3 specs.py
    deps:
      - ../ModelicaByExample
      - specs.py
      - source/_sphinxext/xogeny
    outs:
      - plots
      - results/allres.mos
      # TODO: get rid of json files?
      # TODO: get rid of non-allres .mos files
  build-results:
    wdir: text/results
    cmd: make results_files exes.tar.gz tidy
    deps:
      - allres.mos
      - ../../ModelicaByExample
    outs:
      - exes.tar.gz
