stages:
  build-specs:
    cmd:
      - mkdir -p results/json
      - mkdir -p plots
      - python3 specs.py
    deps:
      - ../ModelicaByExample
      - specs.py
      - source/_sphinxext/xogeny
    outs:
      - plots
      - results/allres.mos
      # TODO: get rid of json files?
      # TODO: get rid of non-allres .mos files
  build-results:
    wdir: results
    # Note: Decay1 should fail, ThreeS just needs tighter tolerance
    # TODO: What is going on with ThirdS?  Seems to go unstable.
    cmd: make results_files exes.tar.gz tidy
    deps:
      - allres.mos
      - ../../ModelicaByExample
    outs:
      - exes.tar.gz
