name: build

on:
  push:
    branches: [master]

jobs:
  generate_results:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mtiller/book-builder-image:v0.1.1
    steps:
      - name: Mark checkout directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Restore DVC Cache
        id: dvc-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .dvc/cache
          key: dvc-cache-key
      - name: Make PDFs
        run: make env pdfs
      - name: Upload Executables
        uses: actions/upload-artifact@v3
        with:
          name: exes.tar.gz
          path: text/results/exes.tar.gz
      - name: Generate JSON
        run: make env json
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: text/build
      - name: Save DVC Cache
        id: dvc-cache-save
        uses: actions/cache/save@v3
        with:
          path: |
            .dvc/cache
          key: dvc-cache-key
  generate_korean_site:
    runs-on: ubuntu-latest
    container:
      image: node:12
    steps:
      - name: Mark checkout directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Publish Korean Site
        run: make korean_site
      - name: Archive Korean Site
        uses: actions/upload-artifact@v3
        with:
          name: korean-site
          path: out

  publish_korean_site:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Mark checkout directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download Korean Site
        uses: actions/download-artifact@v3
        with:
          name: korean-site
      - name: Install netlify-cli
        run: npm install -g netlify-cli
      - name: Deploy Korean Site
        run: npx netlify deploy --prod --dir=out
